

# 所有源文件列表
SOURCES = pedump.cpp

# exe EXE or dll DLL
TARGET_TYPE = exe

# bin name，如果留空，则使用ProjectName
TARGET = pedump

# 向代码输入宏定义等额外的编译选项
CFLAGS = /D "WIN32" /EHsc /Gy /Gd /GS- /MT
MY_LIBS = 
SYS_LIBS =
LFLAGS = /SUBSYSTEM:CONSOLE

###################################
!INCLUDE ..\Comm_MakeFile